[package]
name = "rud-internal"
version = "0.1.0"
authors = ["gamma-delta"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = {git = "https://github.com/gamma-delta/rlua-arcmux-userdata"}